### ISSUE TITLE
Preview image is flipped 180 horizontally

### ISSUE THREAD

**Issue by prazjain** [jrvansuita/PickImage#1]
Hi,
I am testing your picker for a project, and I have seen some issues.
When I click a selfie in portrait mode:
1) The image shown in preview is flipped 180 degrees horizontally. So my left becomes right and vice-versa.
2) The actually image that is displayed in imageview in the return callback, is rotated left by 90 degrees. So actually I will need to turn it right 3 times to see image correctly.

Other than these I like your library and plan to use it once these issues are fixed.

Thanks

**Comment by jrvansuita** [comment]
@prazjain I understand. This issue only occurs when you use the front camera, right?

I searched all over the internet to find a solution for this problem. But it seems to be more about the front-camera than the library algorithm. When onActivityResult is reached, the bitmap already flips 180 degrees. I can not detect if it was used the front or the back camera to take the photo. If I could, I would simply flip the image every time.

Trying to help you, I just created this attribute on PickSetup class.
```
PickSetup setup = new PickSetup();
setup.setFlip(true);
PickImageDialog.on(MainActivity.this, setup);
```

Don't forget to use the last version of the library.

**Comment by prazjain** [comment]
Thanks a lot

**Comment by jawadturk** [comment]
the problem actually still exist you have to handle the captured image rotation , i will not use this library for now until it get fixed.

**Comment by jrvansuita** [comment]
@jawadturk It's necessary a little thinking to understand whats going on when you take a photo from the front camera. First of all, try now to take a photo, using your front camera and see the result. You will notice that, your default android camera, flipped the image. Do your face appears to be flipped on the image, right?

Let's think a little bit. When the image is been flipped? The answer is: when you is seeing yourself before took the photo! Your camera app is flipping the image for you, to have a better notion on whats the image will be. 

Try another thing to finally understand what I mean. Using your front camera, point it to an object in front of you. You are seeing the back of your phone right? Now, take the photo without flip back your phone. Let's check the result. If you now, look at the pic you just took, it's not flipped! The image is right as your are seeing.

This is a common camera behavior, there's nothing to do with it, the image is not flipped.
