### ISSUE TITLE
bug when dialog is opened from an activity that implements onActivityResult

### ISSUE THREAD

**Issue by ofir500** [jrvansuita/PickImage#102]
Apparently if you start the PickImageDialog from an activity that already implements onActivityResult,
then when the dialog returns it calls my own activity's onActivityResult instead of the dialog's implementation of it.

I got around the issue by saving a reference to the dialog and then calling dialog.onActivityResult from my activity's onActivityResult

It turns out to be a common problem:
https://inthecheesefactory.com/blog/how-to-fix-nested-fragment-onactivityresult-issue/en

**Comment by benoffi7** [comment]
I have the same problem. can you paste your workaround?

I save the dialog in a var but onPickResult in PickImageDialog a1 = PickImageDialog.build(setup)
                        .setOnPickResult does not called

Thanks!
