### ISSUE TITLE
Latest dependency

### ISSUE THREAD

**Issue by ronakmob** [jrvansuita/PickImage#103]
Hi,

Its bit confusing to find latest dependency. 

As per releases its ` v2.1.0` and as per release order number `2.2.4`. 

I would be thankful for your help.

**Comment by molaeiali** [comment]
Probably there is a problem here, I have fixed some issues with video picking and it is merged into the master branch, but it is released as v2.1.0 but before that, it is 2.2.4! I am trying to use v2.1.0 as it has my merged commit, but after syncing project, I get a library with no setVideo() method!! I think the tag should be 2.2.5

**Comment by mjumayev** [comment]
use this
compile 'com.github.jrvansuita:PickImage:398c9237d3'

**Comment by bdauer** [comment]
We're running into the same issue. Trying to import a build that includes this fix:

https://github.com/jrvansuita/PickImage/issues/72

as we're hitting that bug on production in our app. Any suggestions would be hugely helpful.
