### ISSUE TITLE
Provider authority conflict

### ISSUE THREAD

**Issue by francescopedronomnys** [jrvansuita/PickImage#11]
Hello,
I would like to point out that multiple apps that use your library cannot be installed on the same device because the provider authority is always `com.vansuita.pickimage.provider`, so it procude a conflict during installation.

Probably an option could be added to allow the app to provide the authority to PickSetup, and then override the authority name on his manifest in this way:
`<provider
   tools:replace="android:authorities"
   android:name="android.support.v4.content.FileProvider"
   android:authorities="${applicationId}.com.vansuita.pickimage.provider"
   android:exported="false"
   android:grantUriPermissions="true">
   <meta-data
      android:name="android.support.FILE_PROVIDER_PATHS"
       android:resource="@xml/provider_paths"/>
</provider>`

Thanks,
Francesco

**Comment by jrvansuita** [comment]
Great to see your contribution. One person already had ask my about it. I just commited your pull, but can you update the readme and the sample app to provide information on how to declare the provider on manifest and setting the authority?

**Comment by jrvansuita** [comment]
Authority now is mandatory to create new PickSetup object.
