### ISSUE TITLE
[Question] - Latest version

### ISSUE THREAD

**Issue by GuilhE** [jrvansuita/PickImage#114]
Which is the correct latest version? 
`implementation 'com.github.jrvansuita:PickImage:2.2.4'`
or
`implementation 'com.github.jrvansuita:PickImage:v2.1.1'`

I ask because JitPack says it's **2.2.4** but your latest release tag is **v2.1.1**. Funny thing, if I download **2.2.4** it seems the code is newer than **v2.1.1**. I'm confused ^^

**Comment by bekirdursun** [comment]
**v2.5** - **2.5** - **2.2.4**

which one? (https://jitpack.io/#jrvansuita/PickImage)
