### ISSUE TITLE
The version numbers don't follw sematic versioning

### ISSUE THREAD

**Issue by build3r** [jrvansuita/PickImage#121]
The versions are out of order
**v2.1.1** was released on  **Sep 5, 2019**
**v2.2.4** was released on  **Aug 26, 2018** 
On jitpack v 2.2.4 is shown as latest.
Due to this people like me might get confused and use a older version.
Please have a look at it when you ever you are free.

**Comment by Siwy160** [comment]
True, it is really confusing that highest version is not actually the latest.

**Comment by jrvansuita** [comment]
Ok, fixed
