### ISSUE TITLE
androidx compatibility not provided.

### ISSUE THREAD

**Issue by ChiangChu** [jrvansuita/PickImage#122]
Currently the library does not work with androidx libraries. When I want to change the FileProvider to the androidx one, I get an merge error:
Error: Element provider#androidx.core.content.FileProvider at AndroidManifest.xml:53:9-63:20 duplicated with element declared at AndroidManifest.xml:41:9-51:20

Seems like it cannot override the manifest defined in the library.

Here is the provider code snippet.

```
        <provider
                android:name="androidx.core.content.FileProvider"
                android:authorities="${applicationId}.com.vansuita.pickimage.provider"
                android:exported="false"
                android:grantUriPermissions="true"
                tools:replace="android:authorities">
            <meta-data
                    android:name="android.support.FILE_PROVIDER_PATHS"
                    android:resource="@xml/picker_provider_paths"
                    tools:replace="android:resource"/>
        </provider>
```

**Comment by jrvansuita** [comment]
Make a PR pls
