### ISSUE TITLE
class file for androidx.fragment.app.DialogFragment not found

### ISSUE THREAD

**Issue by mehrdaddolatkhah** [jrvansuita/PickImage#124]
hello,
when after a time open my project and try to build it, I got this error:

`DialogFragment
        PickImageDialog.build(new PickSetup())
                       ^
  class file for androidx.fragment.app.DialogFragment not found`

may please guide me on how I can fix this problem?

**Comment by Neotoon** [comment]
Same problem, Hoping for a response

**Comment by fsevenm** [comment]
On Kotlin the error is like `Cannot access 'androidx.fragment.app.DialogFragment' which is a supertype of
'com.vansuita.pickimags.dialog.PicklmageDialog', Check your module classpath for missing or
conflicting dependencies` with v2.5 or using tag `+`. Using v2.2.4 as @Neotoon suggested fix the issue for now.

**Comment by majedalmoqbeli** [comment]
Use this code 

```
PickImageDialog.build(new PickSetup().setSystemDialog(true))
                    .setOnPickResult(new IPickResult() {
                        @Override
                        public void onPickResult(PickResult r) {
                            // get your image here 
                        }
                    }).show(getActivity().getSupportFragmentManager());
```
