### ISSUE TITLE
Facing Issue while selecting image from gallery.

### ISSUE THREAD

**Issue by dipen-solulab** [jrvansuita/PickImage#13]
Getting below error while selecting image from MI phone gallery : 

"Attempt to invoke interface method 'int android.database.Cursor.getColumnIndexOrThrow(java.lang.String)' on a null object reference."

**Comment by jrvansuita** [comment]
Hello, can you check if my last commit fixed this issue?

commit 37986409a7afacbefc5505857adefb87d0d08d9e

**Comment by dipen-solulab** [comment]
@jrvansuita Thanks, it's working in your sample code. Will you please release it with new gradle version.

**Comment by jrvansuita** [comment]
Done  compile 'com.github.jrvansuita:PickImage:v2.0.2'
