### ISSUE TITLE
override "onPickResult" on Fragment not working

### ISSUE THREAD

**Issue by DiegoValadz** [jrvansuita/PickImage#134]
I need to get pickResult on the fragment where I made the call, but interface only works overriding the method in the Activity (As it says in the instructions), is there any way to do this?

**Comment by LJOSS** [comment]
What Android version do you use?

**Comment by majedalmoqbeli** [comment]
Use the code 
`PickImageDialog.build(new PickSetup().setSystemDialog(true))
                    .setOnPickResult(new IPickResult() {
                        @Override
                        public void onPickResult(PickResult r) {
                            // get your image here 
                        }
                    }).show(getActivity().getSupportFragmentManager());`
