### ISSUE TITLE
Not working on Andorid 10

### ISSUE THREAD

**Issue by LJOSS** [jrvansuita/PickImage#135]
Hi,
I have a BIG problem
Yours library doesn't work on Android 10 on  Android 9 it works
I have PickImage at Fragment
When i took a photo and no callback occurred
When i take photo from gallery it works

Picasso.with(getContext()).load(new File(imagePath)).into(profile);

**Comment by LJOSS** [comment]
Resolve 
Following https://stackoverflow.com/a/60797239/10329425

**Comment by yogeshpaliyal** [comment]
Fixed
