### ISSUE TITLE
Camera issue in android 4.4.4 (java.lang.SecurityException: Permission Denial)

### ISSUE THREAD

**Issue by dipen-solulab** [jrvansuita/PickImage#14]
Application is crashing while capturing image from camera.

Getting : 
java.lang.SecurityException: Permission Denial: opening provider android.support.v4.content.FileProvider from ProcessRecord{42cbe3e0 19266:com.sec.android.app.camera/u0a80} (pid=19266, uid=10080) that is not exported from uid 10281

**Comment by dipen-solulab** [comment]
Hi,
I have done some changes in your library code.

Added below lines In Util class in launchCamera() and it's working, Please verify.

List<ResolveInfo> resInfoList = frag.getActivity().getPackageManager().queryIntentActivities(intent, PackageManager.MATCH_DEFAULT_ONLY);
            for (ResolveInfo resolveInfo : resInfoList) {
                String packageName = resolveInfo.activityInfo.packageName;
                frag.getActivity().grantUriPermission(packageName, uri, Intent.FLAG_GRANT_WRITE_URI_PERMISSION | Intent.FLAG_GRANT_READ_URI_PERMISSION);
            }

**Comment by askarsyzdykov** [comment]
+1 
if "minifyEnabled true"

**Comment by jrvansuita** [comment]
Got you, I fixed it in the new release version.
