### ISSUE TITLE
Gallery Intent does not List gallery app

### ISSUE THREAD

**Issue by build3r** [jrvansuita/PickImage#148]
The gallery option list all documents and and shows images recent images. But it does not list the default gallery ap or or Google photos app which can have different folders for easy selection of picture.

The issue is because the Intent is set to [open a document ](https://github.com/jrvansuita/PickImage/blob/0a660a328465f32ae81b7d5bea6b27dc97385164/library/src/main/java/com/vansuita/pickimage/resolver/IntentResolver.java#L185)
I was able to list the gallery apps by use the below intent
```
        val galleryIntent = Intent(Intent.ACTION_GET_CONTENT)
        galleryIntent.addCategory(Intent.CATEGORY_OPENABLE);
        galleryIntent.addFlags(FLAG_GRANT_READ_URI_PERMISSION);
        galleryIntent.addFlags(FLAG_GRANT_WRITE_URI_PERMISSION);
        galleryIntent.setType("image/*")
```

**Comment by jrvansuita** [comment]
Yes, you are right. Changing this action on next release

**Comment by build3r** [comment]
Did we test this? I had created a PR with the change but the change was causing crashes.
