### ISSUE TITLE
Can't use EPickTypes.Camera without EPickTypes.Gallery appearing

### ISSUE THREAD

**Issue by bmbariah** [jrvansuita/PickImage#15]
In the latest build, including your sample demo both provides Camera and Gallery providers appear regardless of whatever my choice is. I select EPickTypes.Camera ONLY and gallery still appears and vice versa

Edit: Issue is only present when 'setup.setSystemDialog' is set to false.
Testing on 7.1.1

**Comment by jrvansuita** [comment]
Fixed, get the last release please.
