### ISSUE TITLE
@string/app_name is marked as private

### ISSUE THREAD

**Issue by Adam0220** [jrvansuita/PickImage#153]
When I used @string/app_name in XML layout; the ide shows me this message (also shows in string file):
The resource @string/app_name is marked as private in com.github.jrvansuita:PickImage:2.5.5
...
...
My question is: 
Could this thing cause a problem for me later?

![Screenshot 2022-03-08 083353](https://user-images.githubusercontent.com/62855678/157181568-f77b92a1-73f1-437f-aa56-e47d737169fb.png)

**Comment by jrvansuita** [comment]
It's a warning!
