### ISSUE TITLE
I got this error "Installation failed due to: 'INSTALL_FAILED_CONFLICTING_PROVIDER"

### ISSUE THREAD

**Issue by majedalmoqbeli** [jrvansuita/PickImage#157]
When I updated library to v3.0.0 I got this error "Installation failed due to: 'INSTALL_FAILED_CONFLICTING_PROVIDER"

this error only show when I have two apps use the same lib in my device. 

this is my provider:

```
<provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="${applicationId}.com.vansuita.pickimage.provider"
            android:exported="false"
            android:grantUriPermissions="true"
            tools:replace="android:authorities">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/picker_provider_paths" />
        </provider>

```

Thanks

**Comment by jrvansuita** [comment]
The authority, as listed in android:authorities must be unique. What is your ${applicationId} value? Do you have the same value for applicationId in two diff apps?

**Comment by jrvansuita** [comment]
<img width="453" alt="image" src="https://user-images.githubusercontent.com/12175215/174175209-e711d0a6-4743-4177-a892-7a8d652a3c53.png">
You have to define an applicationId in you build.gradle

**Comment by majedalmoqbeli** [comment]
@jrvansuita 
Thank you for reply.
My applicationId is totally different.

![Screenshot 2022-06-17 102646](https://user-images.githubusercontent.com/46192476/174247953-8f0f64d4-8d67-46a0-8053-87953c91fcd8.png)

When I run the app in pic (2) first, then I can't run the app in pic(1).
-If I delete app in pic(2) the app in pic(1) run fine.
-If I go back to `com.github.jrvansuita:PickImage:2.5.4` the app run fine.

**Comment by majedalmoqbeli** [comment]
Any update @jrvansuita ?

**Comment by majedalmoqbeli** [comment]
Thank you it works fine.
