### ISSUE TITLE
Wrong version name for PickImage (3.0.1 -> 3.0.01)

### ISSUE THREAD

**Issue by paolorotolo** [jrvansuita/PickImage#159]
Hey, thanks for the library. 

Just want to report that the latest version is released here as PickImage `3.0.1`. However, gradle can't find the right package because git tag picked by Jitpack, is `3.0.01`. You may want to rename the release here on GitHub to avoid confusion.

Thanks.

**Comment by jrvansuita** [comment]
Fixed, thkx

**Comment by paolorotolo** [comment]
thanks.
