### ISSUE TITLE
Images are not Loading ...

### ISSUE THREAD

**Issue by myinnos** [jrvansuita/PickImage#17]
Its showing simply ` loading ...` bar that's all images are doesnt load to view

**Comment by jrvansuita** [comment]
Can you provide more details? Witch version are you talking about?
Can you give your sample code?

**Comment by myinnos** [comment]
Version `v2.0.6`

And i followed all steps what you mention in [here](https://github.com/jrvansuita/PickImage/blob/master/README.md)

`Note: This issue happens only some times not all the times`

**Comment by jrvansuita** [comment]
Is the issue happing debugging the sample? Can you give witch version of android are you using? Did you tried to check what happing inside de code? This issue never happened to me. I will try to reproduce it using the same android version you are using.

**Comment by bmbariah** [comment]
I can also confirm I'm having this issue..Happens mostly after I try to take another picture via camera, immediately after the first or second one. App is stuck on 'Loading' forever and  Log is only saying 
```java
I/ExifInterface_JNI: Raw image not detected
W/ExifInterface: Skip the tag entry since tag number is not defined: 2
```

**Comment by myinnos** [comment]
Yes as @bmbariah said for me also happens same `issue`! 

Device details : `Android 6.0 MOTO `

**Comment by jrvansuita** [comment]
Ok, sorry for the delay, was traveling. I got the fix. Please check it out.
Look for the last commit. I will release another version.
