### ISSUE TITLE
Images shows as Black screen

### ISSUE THREAD

**Issue by myinnos** [jrvansuita/PickImage#18]
After selecting image from gallery (camera images) shows blank screen

**Comment by jrvansuita** [comment]
Fixed!
```
compile 'com.github.jrvansuita:PickImage:v2.0.8'
```
please!

**Comment by myinnos** [comment]
same [issue ](https://github.com/jrvansuita/PickImage/issues/18) even in latest version `(v2.0.8)`

Tested in `HTC Desire 816`

**Comment by jrvansuita** [comment]
Hi @myinnos, It will be really helpful if you provide you sample code. Or even better, try to debug it if it's happing in the projects sample app too. I really never saw this issue.

**Comment by myinnos** [comment]
Its happening, if i selected big/large images(CAMERA images), please test with some high end images

Example [image ](http://wallpapercave.com/wp/EE5G3eV.jpg)

**Comment by jrvansuita** [comment]
No problem at all. Wait, you are the same guy who opened the issue #19. You should fix the provider error first. No provider, no images picking....


![screenshot_20170221-100027](https://cloud.githubusercontent.com/assets/12175215/23165798/a21a7e72-f81c-11e6-8d20-f5f2dc8a9ba4.png)

**Comment by myinnos** [comment]
Thats cool! 👍 Thank you

**Comment by jrvansuita** [comment]
Got it working?

**Comment by myinnos** [comment]
Yes Working!

**Comment by jrvansuita** [comment]
hahhaha, Great! Whats it was?
