### ISSUE TITLE
I would like to use my implementation from the choice

### ISSUE THREAD

**Issue by josinaldobarbosa** [jrvansuita/PickImage#2]
Ex.: 

```
PickImageDialog.on(..., new Listener(){
            @Override
            public void cameraClick() {
                // my implementation
            }

            @Override
            public void galeryClick(){
               // my implementation
            }
        });
```
Without returning the image (bitmap or uri)
Optional listener not on object because in my case I have more than one in the same Activity

I think the lib would be more generic :)

**Comment by jrvansuita** [comment]
Sure! Take a look at readme file. 

This func was implemented on v1.0.4.
