### ISSUE TITLE
How to use PickImage without showing dialog?

### ISSUE THREAD

**Issue by engintekin** [jrvansuita/PickImage#21]
Hello,

Is it possible to open camera or gallery without showing the dialog? If yes what's the best way to do that? 

Thanks,

**Comment by jrvansuita** [comment]
Yep!

```
new IntentResolver().launchCamera();
new IntentResolver().launchGallery();

```

You should take a look on what the library does internally.

**Comment by build3r** [comment]
@jrvansuita the  launchCamera expects a fragment as listener with no way to pass an activity
```
public void launchCamera(Fragment listener)
```
We can add a overloaded function with accepts activity.
