### ISSUE TITLE
Set a image size (width && height)

### ISSUE THREAD

**Issue by sayah-y** [jrvansuita/PickImage#22]
Hello,

I want to define a image size:
`
private static int PHOTO_WIDTH = 800;
private static int PHOTO_HEIGHT = 600; 
`
I see in the setup:
`
.setImageSize(XXX)
`
Can you give me more details please to define a width and a height ?

Thanks for your work.

**Comment by jrvansuita** [comment]
Hi @sayah-y, Today, it's not possible to set width and height to the image. Try to do it in you `ImageView`. The mentioned method `setImageSize()` is a scale method. Here you can set the max scale size. Look at the code above to understand what this value do.

`ImageHandler.decode();`

```
       // Find the correct scale value. It should be the power of 2.
        int width_tmp = options.outWidth;
        int height_tmp = options.outHeight;
        int scale = 1;
        while (true) {
            if (width_tmp / 2 < setup.getImageSize() || height_tmp / 2 < setup.getImageSize())
                break;

            width_tmp /= 2;
            height_tmp /= 2;
            scale *= 2;
        }

        // Decode with inSampleSize
        BitmapFactory.Options o2 = new BitmapFactory.Options();
        o2.inSampleSize = scale;
        Bitmap bitmap = decodeStream(context.getContentResolver().openInputStream(uri), null, o2);

```

**Comment by sayah-y** [comment]
I think it will be a good feature for this library.
Ok. Thanks for your answer.

**Comment by jrvansuita** [comment]
https://github.com/jrvansuita/PickImage/releases/tag/2.1.1
