### ISSUE TITLE
Didn't show camera icon in dialog

### ISSUE THREAD

**Issue by mihanic89** [jrvansuita/PickImage#24]
Hello @jrvansuita ,
Didn't show camera icon in dialog if there is now camera permission before accepted. If in main activity request camera permissiom and after call picker dialog it show camera icon. This applies to signed apk. No sign apk work correct and show both icon.

**Comment by jrvansuita** [comment]
Just tried to reproduce your issue and everything worked fine to me. Used an app published [here](https://play.google.com/store/apps/details?id=com.vansuita.passwordvault) to test. Are you using the last library release? 

Me test was:
 * 1  - Unnistaled the app;
 * 2 - Installed the app;
 * 3 - Checked no permission for camera granted;
 * 4 - Triggered the dialog (The camera icon is there);
 * 5 - Pressed the camera button(Was ask for the permission);

![screenshot_2017-04-08-13-56-04](https://cloud.githubusercontent.com/assets/12175215/24831344/275ef85e-1c6e-11e7-966d-85b4dc7941bc.png)
![screenshot_2017-04-08-13-55-57](https://cloud.githubusercontent.com/assets/12175215/24831343/26e78904-1c6e-11e7-979d-7e52361c8443.png)
