### ISSUE TITLE
dialog.dismiss(); usage

### ISSUE THREAD

**Issue by canberkcakmak** [jrvansuita/PickImage#25]
Hi, thanks for awsome lib. I have a problem about dismiss. 
 implementation is in click button and in onCreate like this : 

```
 PickSetup setup = new PickSetup()
                                                        .setTitle("Lütfen Seçiniz")
                                                        .setGalleryButtonText("Galeri")
                                                        .setCancelText("İPTAL")
                                                        .setButtonOrientation(LinearLayout.HORIZONTAL);

                                                PickImageDialog.build(setup).show(NewContentActivity.this);
```

and i m using implements IPickClick 

```
    @Override
    public void onGalleryClick() {

        }

    @Override
    public void onCameraClick() {

    }

```

i want to user when click camera or gallery dissmis dialog however i cant use this. Please give more example about this. Thank you

**Comment by jrvansuita** [comment]
```
PickImageDialog dialog = PickImageDialog.on(...);
dialog.dismiss();
```

**Comment by canberkcakmak** [comment]
I saw it but what ist the (...) by the way dialog already defined in oncreate so, it throws null exeption.

**Comment by jrvansuita** [comment]
Sorry, it's `PickImageDialog.build(setup)`.

Keep a referente for PickImageDialog and call.
dialog.dismiss();

**Comment by canberkcakmak** [comment]
I'm not on computer so i can not testing it. Thank you

**Comment by canberkcakmak** [comment]
thank you it works.
