### ISSUE TITLE
onClick listener does´n work

### ISSUE THREAD

**Issue by andrey-kaiser** [jrvansuita/PickImage#26]
Hi! First of all, let me thank you for an awesome library!

It looks like setOnClick(new IPickClick() {})  does´n work. I´ve tried with latest version as well as with sample app which uses version 2.0.4. I´ve just tried to log which option user select to implement my own business logic, but it simply prints nothing.

What I´m trying to achieve is to add photo to android gallery in case user selects Camera option, so I need to differ Camera from Gallery option. Check out the issue please.

Thanks in advance!

**Comment by jrvansuita** [comment]
Thanks buddy!
Can you show me you piece of code?

**Comment by andrey-kaiser** [comment]
In a sample app, comment the following
`PickImageDialog.build(setup).show(this);`

Un-comment and modify an example of click handling so it looks like this:

```
PickImageDialog.build(setup).setOnClick(new IPickClick() {
            @Override
            public void onGalleryClick() {
                Log.d("~", "onGalleryClick");
            }

            @Override
            public void onCameraClick() {
                Log.d("~", "onCameraClick");
            }
        }).show(this);
```

Then I expect to see a corresponding message when selecting Camera or Gallery option, but it prints nothing. All I´m really trying to do is set a flag that user selects Camera to add the photo to gallery later.

**Comment by jrvansuita** [comment]
Okay @andrey-kaiser ! Got the issue and fixed it.

If you don't want to update the library with the new version, you can still use the old release and do the follow:

`PickImageDialog.build(setup).setOnClick(this).show(this);`

Then, make your activity implements IPickResult and override the methods:
```
  @Override
    public void onGalleryClick() {
        Toast.makeText(SampleActivity.this, "Gallery Click!", Toast.LENGTH_LONG).show();
    }

    @Override
    public void onCameraClick() {
        Toast.makeText(SampleActivity.this, "Camera Click!", Toast.LENGTH_LONG).show();
    }
```

Otherwise you should move to the next release and use like you already did. It's working now.
