### ISSUE TITLE
Calling show() without parameters

### ISSUE THREAD

**Issue by SebastienFCT** [jrvansuita/PickImage#28]
Hi jrvansuita!

Is there any way to show the `PickImageDialog` without passing any parameters?

Similar to what we can actually do with `android.app.Dialog`.

The point would be to make `PickImage` independent and working as long as you provide it a context where it can live.

In my case, I'm trying to open a normal dialog from my ListAdapter in one case and opening the `PickImage` in the other case, but I'm stuck here where I need to pass a the `getSupportFragmentManager`

**Comment by jrvansuita** [comment]
Hi @SebastienFCT, sorry but it's not possible to have a method like `show(Context)`.
If you check the implementation, I'm using a class called `DialogFragment`. Only with this class I'm able to implement the onActivityResult and get the image from the intent. Even the default show() methods from DialogFragment needs a instance of FragmentTransation or FragmentManager.

**Comment by SebastienFCT** [comment]
Thank you for these explanations, I checked and understand your work better now 👍
