### ISSUE TITLE
Checking picture on activity result

### ISSUE THREAD

**Issue by LamraniOthmane** [jrvansuita/PickImage#29]
First of all i want to thank you a lot for this library, i have a little issue when i take a picture from the camera i want to allow the user to check his picture before exiting the camera instead.
Thank you for helping me, 
Have a nice day.

**Comment by jrvansuita** [comment]
Yeah, Thank you! That's a default behavior when you use the camera app. First you take the pic and the camera app shows your pic. At this moment you have to click on OK button to run the activity result.

**Comment by LamraniOthmane** [comment]
Thank you for answering so quickly, unfortunately i don't see any OK button.
Once i take a picture from the camera  or select any picture from the gallery, i'm redirected automatically to the choosing menu, and i loose the picture that i just selected.
Please any help ? Here is my code, did i do something wrong ?

![capture](https://cloud.githubusercontent.com/assets/26097552/25001412/578092f4-203d-11e7-851a-da91ac52611d.PNG)

**Comment by jrvansuita** [comment]
@LamraniOthmane Why are you calling show() twice?

**Comment by jrvansuita** [comment]
Test here: https://play.google.com/store/apps/details?id=com.vansuita.pickimage.sample
Check if you got a preview screen when you take the pic.

**Comment by jrvansuita** [comment]
This happens to me. The screen one is the preview, just after taking the pic.
![1](https://cloud.githubusercontent.com/assets/12175215/25001881/e40a996a-201d-11e7-9135-f72170d46dd9.png)
![2](https://cloud.githubusercontent.com/assets/12175215/25001887/e987d6be-201d-11e7-901c-bc8e79353737.png)

**Comment by LamraniOthmane** [comment]
woow, i didn't pay attention, i tried to remove it but i have the same issue. And i don't have the preview screen. Even when i installed your application i don't have the preview screen, the image is directly shown in the box. 
I am using Sony Xperia Z2 Android 6.0

**Comment by jrvansuita** [comment]
Ok, This is a default behavior, I think we can't achieve it using the default camera. At least, try to find any settings to enable the preview screen on your camera app.

Install this apps:
https://play.google.com/store/apps/details?id=com.motorola.camera
https://google-camera.br.uptodown.com/android

Try use the default system dialog and choose one of this apps.

`setup.setSystemDialog(true); `

**Comment by LamraniOthmane** [comment]
Thank you @jrvansuita I will try to get the image and set it to an imageView with two buttons.

**Comment by LamraniOthmane** [comment]
@jrvansuita I tried to run my code in another device and it woks. The problem is maybe my phone is damaged, because i use it for running. 
I would like to thank you for your hard work on this library, finally i have a little more question: 
Do you have any tutorial for uploading images to the server ? 
Thank you in advance

**Comment by jrvansuita** [comment]
What server are you talking about?

**Comment by LamraniOthmane** [comment]
I was looking for how to upload files from my android application to my server, so i found this tutorial and it works great ! 
Thank you @jrvansuita  
Here is the link, maybe it could be helpful someday: 
 https://www.simplifiedcoding.net/android-upload-image-to-server/
