### ISSUE TITLE
Returned Image is Rotated by 270 degrees If selected by Camera

### ISSUE THREAD

**Issue by AbhisheKundalia** [jrvansuita/PickImage#30]
Thank you So much for the Awesome work.

However I am facing image rotation by 270 degrees in ImageView when Image is selected using Camera Intent, It works completely fine if image is selected using Gallery with no Rotation.

Please help me if we have a method to know if the image was selected using Camera or gallery? So that I can rotate the retrieved image accordingly in my Code.

**Comment by jrvansuita** [comment]
There's a method in this lib called  `rotateIfNeeded()`. Can you try to debug this method in your device?
All devices tested by me works great.

**Comment by qadir227** [comment]
@jrvansuita how to use this method?
I add the library to my project. I think its the latest version
`compile 'com.github.jrvansuita:PickImage:2.0.1'`

I am not able to use the function you have pointed out i.e rotateIfNeeded().

here is my code. Please read comments

`layout_driver_image.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                PickImageDialog.newInstance(new PickSetup())
                        .setOnPickResult(new IPickResult() {
                            @Override
                            public void onPickResult(PickResult r) {
                                //TODO: do what you have to...

                                if (r.getError() == null) {
                                    
                                  

                                    //Bitmap bitmap =
                                    img_driver_image.setImageBitmap(r.getBitmap()); // Image is rotated taken from both camera front and rear 
                                    String image_path = r.getPath();
                                    Log.e("image_path", image_path);
                                    
                                } else {
                                    //Handle possible errors
                                    //TODO: do what you have to do with r.getError();
                                    Toast.makeText(getActivity(), r.getError().getMessage(), Toast.LENGTH_LONG).show();
                                }


                            }
                        }).show(getChildFragmentManager(), "DriverAddDocumentsFragment");
            }
        });`

**Comment by jrvansuita** [comment]
No, this is a private method, you should test it "rotateIfNeeded", using the sample project, not your project.

**Comment by qadir227** [comment]
@jrvansuita you mean I can't use in my project? I have to rotate image in my project. Its requirment. Any workarround

**Comment by jrvansuita** [comment]
I mean, you should run and debug the sample project using your device to check what is happening and why you have the issue.  The code is running with no issues like yours on many devices. You should debug here `ImageHandler.getRotationFromCamera()`;

By the way, I changed the method ImageHandler.rotate(bitmap, degress) to public. So, now you can call it in you application how you need.
