### ISSUE TITLE
Camera returning the same image which captured first time only

### ISSUE THREAD

**Issue by Hanzala717** [jrvansuita/PickImage#33]
I choose camera for image, captured Image and it's returning the captured image that's well but I want to recapture image I choose camera again captured an image but I got the image I captured first. Even I tried multiple captures but only first image I got always.

**Comment by zarvedan** [comment]
I had the same issue. To resolve it I had to get the bitmap from pickResult instead of the path :

` Glide.with(this)
                    .load(Functions.getByteArrayFromBitmap(pickResult.getBitmap()))
                    .asBitmap() ...`

with :
` public static byte[] getByteArrayFromBitmap(Bitmap bitmap) {
        ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
        if (bitmap != null) {
            bitmap.compress(Bitmap.CompressFormat.PNG, 90, byteArrayOutputStream);
            return byteArrayOutputStream.toByteArray();
        } else
            return null;
    }`

**Comment by Hanzala717** [comment]
but I needed uri

**Comment by jrvansuita** [comment]
Why? Could you elaborate more you issue?

**Comment by Hanzala717** [comment]
If I pick an image uri it works fine
But if I try to get another image again then bitmap is new one but uri will be old image

**Comment by huangenyan** [comment]
I meet the same problem. The problem is when I use your library to take a photo, the taken photo will save in the same URI as the old photo and the old photo is overwritten.  It would be nice that the taken photos are saved at different URIs so all of them are preserved.

**Comment by mhd-adeeb-masoud** [comment]
Having same problem here with glide

**Comment by IvanJian** [comment]
Same issue

**Comment by Wolf00Bomber** [comment]
Any resolution on this issue?

**Comment by jrvansuita** [comment]
Ok, cleaning the temp directory every camera start. I think it will fix the problem.

**Comment by msaenz424** [comment]
Hello @jrvansuita, I like your library but I'm still facing the same issue. The gallery part works fine, but when I take a picture the second time and after, it always picks the photo that was taken the first time only, even though I restart the app. Seems like the file.delete() statement in the library is being ignored.

**Comment by gsavvid** [comment]
This issue is still not resolved unfortunately.

**Comment by jrvansuita** [comment]
Guys, I'm looking for some ones the keep contribution to this project. I'm out of time to make any fixes right now. I would be great to see some contributions from you guys.
