### ISSUE TITLE
Turn-by-Turn Navigation instruction from pgRouting Heading (Android)

### ISSUE THREAD

**Issue by LamraniOthmane** [jrvansuita/PickImage#35]
Hello guys, 
I am using pgRouting request so i get the heading result of each edge.
I want to show turn by turn message when the distance between my current position and the start of the next edge is less than 50 meters.
I do this inside the onLocationChanged method. But i have lag because the code is executed each millisecond due to location manager.
Please i need help, thanks in advance.

**Comment by jrvansuita** [comment]
I think you misunderstood the project issue page.
