### ISSUE TITLE
Crop Selected Image

### ISSUE THREAD

**Issue by rahul260792** [jrvansuita/PickImage#36]
Is it possible to crop the selected image?

**Comment by jrvansuita** [comment]
Hello there, not yet! Can you elaborate more? How could this feature work?

**Comment by rahul260792** [comment]
Something like, As soon as I select the image there we can have an option to crop the image and return the cropped image `onPickResult(PickResult r)`.

**Comment by jrvansuita** [comment]
Cool, That would be a great feature. Unfortunately, I will have zero time to implement something like that for the next months. Can you help me with this func? It will be a great contribution for this project. Give me a hand on this creating a pull request. :)

**Comment by rahul260792** [comment]
I was able to do the above said using default Android Crop intent in case the user picks the image from gallery but its not working with camera.

**Comment by jrvansuita** [comment]
I'm still looking for help on this one.

**Comment by LittleSigh** [comment]
Are you still looking for a solution @jrvansuita ?
I solved it like this:

My onPickResult(){} Method looks like this:

`@Override
    public void onPickResult(PickResult pickResult) {
        if(pickResult.getError() == null){
            Intent cropIntent = new Intent("com.android.camera.action.CROP");
            // indicate image type and Uri
            cropIntent.setDataAndType(pickResult.getUri(), "image/*");
            // set crop properties
            cropIntent.putExtra("crop", "true");
            // indicate aspect of desired crop
            cropIntent.putExtra("aspectX", 1);
            cropIntent.putExtra("aspectY", 1);
            // indicate output X and Y
            cropIntent.putExtra("outputX", 256);
            cropIntent.putExtra("outputY", 256);
            // retrieve data on return
            cropIntent.putExtra("return-data", true);
            // start the activity - we handle returning in onActivityResult
            startActivityForResult(cropIntent, 2);
        } else {
            Toast.makeText(getApplicationContext(),pickResult.getError().getMessage(), Toast.LENGTH_LONG).show();
        }
    }`

And my onActivityResult(){} looks like this:

`@Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data){
        super.onActivityResult(requestCode, resultCode, data);
        if (requestCode == 2 && resultCode == RESULT_OK){
            //get the returned data
            Bundle extras = data.getExtras();
            //get cropped image as bitmap
            Bitmap bitmap = extras.getParcelable("data");
            Glide.with(getApplicationContext()).load(bitmap).apply(RequestOptions.circleCropTransform()).into(mProfilbild);
        }
    }`

I also use Glide for applying a circlecrop to the image. If you want to just use the cropped Image you have to use something like:

`@Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data){
        super.onActivityResult(requestCode, resultCode, data);
        if (requestCode == 2 && resultCode == RESULT_OK){
            //get the returned data
            Bundle extras = data.getExtras();
            //get cropped image as bitmap
            Bitmap bitmap = extras.getParcelable("data");
            yourImageView.setImageBitmap(bitmap);
        }
    }`

I hope this is helpfull!
