### ISSUE TITLE
App crashed after selecting image from gallery

### ISSUE THREAD

**Issue by qadir227** [jrvansuita/PickImage#46]
App crashed after selecting image from gallery

crash log is pointing to line number 38 of AsyncImageResult.java and is nullpointer exception, It crashed once and lost the crash log. 

I am using it in a fragment

**Comment by jrvansuita** [comment]
More information is needed to test it. Wich device were you using? Paste here the stack trace.

**Comment by qadirsuh** [comment]
yes, will do it once I get the crash again. I just the lost the stack trace.
btw the device is LG-AKA you can check the specs here
http://www.gsmarena.com/lg_aka-7148.php

**Comment by cbriseno** [comment]
@qadir227 Maybe you are missing runtime permissions for reading the external storage on devices prior to Android 6.
