### ISSUE TITLE
No Android 8.0 support

### ISSUE THREAD

**Issue by porkyhead** [jrvansuita/PickImage#47]
Hi

When targeting api 26 I am able to pick an image from gallery, but as soon as I capture an image and confirm it I get the following error in PickResult:
"java.lang.SecurityException: Failed to find provider  for user 0; expected to find a valid ContentProvider for this authority"

Everything works just fine when targeting api 25.

I'm testing on Android 8.0, Pixel and using version 2.1.4 of PickImage.

Any suggestions?

**Comment by jrvansuita** [comment]
Nope, can you help debugging this error on Android 8.0? I don't have that OS.

**Comment by porkyhead** [comment]
Can you try it out on an Emulator with Android 8.0? Just remember to set targetApi = 26.

What info do you want to start debugging?

**Comment by danielpassos** [comment]
@jrvansuita  I'm having a problem with Android 8.0 when using the camera

```
java.lang.SecurityException: Failed to find provider  for user 0; expected to find a valid ContentProvider for this authority
```

<img width="1039" alt="screenshot 2017-11-13 12 18 42" src="https://user-images.githubusercontent.com/13337/32730004-d3138994-c86c-11e7-8b2e-fd75194a056c.png">

https://developer.android.com/about/versions/oreo/android-8.0-changes.html#ccn

**Comment by airmax93** [comment]
+1

**Comment by porkyhead** [comment]
@jrvansuita Any updates?

**Comment by jrvansuita** [comment]
It can be an issue declaring the provider on AndroidManifest.xml. But I don't have any time to seek this at this moment. Anybody can help to fix that?

**Comment by mosamabinomar** [comment]
temp fix. Comment out 
` context.getContentResolver().notifyChange(uri, null);`
in `ImageHandler` decode method
````

    public Bitmap decode() throws FileNotFoundException {
        //Notify image changed
       // context.getContentResolver().notifyChange(uri, null);
```

**Comment by danielpassos** [comment]
I have tested it with @mosamabinomar (version `2.1.5`) and works like a charm.
