### ISSUE TITLE
Null image?

### ISSUE THREAD

**Issue by FelipeRRM** [jrvansuita/PickImage#5]
Nothing happens when I selected a picture from the Gallery or take one from the Camera. Reading the log I can see this:

`D/skia: --- SkImageDecoder::Factory returned null`

The strange thing is that debuging the app, the Bitmap doesn't seem to be null on the callback:

```
@Override
    public void onPickImageResult(Bitmap bitmap) {
        selectedPicture = bitmap;
        imageViewPlaceHolder.setVisibility(View.GONE);
        circleImageView.setVisibility(View.VISIBLE);
        circleImageView.setImageBitmap(selectedPicture);
    }
```

Im on Lollipop 5.1, using an Sony Xperia Z3 if it helps. Tell me if I can help debug this any further.

**Comment by jrvansuita** [comment]
@FelipeRRM Can you get the bitmap debugging? You can check if the param bitmap is null, or you can even see the bitmap on debug mode.

Please, take a look: http://stackoverflow.com/questions/25976141/android-studio-debugger-view-bitmap

What do you mean with: 

> The strange thing is that debuging the app, the Bitmap doesn't seem to be null on the callback:
