### ISSUE TITLE
Support of vector files

### ISSUE THREAD

**Issue by yoali11** [jrvansuita/PickImage#50]
"Fatal Exception: android.content.res.Resources$NotFoundExceptionFile res/drawable/ic_cell_camera.xml from drawable resource ID #0x7f0700b8. If the resource you are trying to use is a vector resource, you may be referencing it in an unsupported way. See AppCompatDelegate.setCompatVectorFromResourcesEnabled() for more info. "

I need a way to pass a drawable as an icon, and not the int reference. To use a Vector image as icon. :-)

**Comment by jrvansuita** [comment]
Paste a code snippet

**Comment by yoali11** [comment]
`
val pickSetup = PickSetup()
                .setCameraIcon(R.drawable.ic_cell_camera)
                .setGalleryIcon(R.drawable.ic_cell_album)
`

This accepts only and _int_ reference to the drawable. I want to use like

`
val pickSetup = PickSetup()
                .setCameraIcon(VectorDrawableCompat.create(activity.resources, R.drawable.ic_cell_album, null))
`

So the argument would be a Drawable.
