### ISSUE TITLE
How to set the size of the image (keeping ratio)? What is setMaxSize()?

### ISSUE THREAD

**Issue by makeitTim** [jrvansuita/PickImage#53]
Thanks for the library!

Our app uploads a photo to an API. I want to control the image resolution and side that's uploaded, but keep the aspect ratio so nothing the user thinks they took in the photo is lost. What's the best way to do this?

In the following code, what does `setMaxSize()` set?
```
        PickImageDialog.build(new PickSetup()
                .setMaxSize(1000)
                .setOnPickResult(new IPickResult() {
                        // ...
                }).show(getActivity());
```
I know it sets something, because changing it results in the following images (from save device, I think xxxhdpi):
```
300
374 x 664 (.25MP), JPG 70% quality, ~25kb

500
747 x 1328 (1MP), JPG 70% quality, ~70kb

1000
1494 x 2656 (4MP), JPG 70% quality, ~250kb

3000
2988 x 5312 (16MP), JPG 70% quality, ~850kb
```
But these results are all different on different devices, with no apparent pattern.

What does `setMaxSize()` mean? I can't find this documented anywhere. Pixels? Density Independent Pixels? Megapixels? Resolution? Compression? Bitmap byte size?

I see the code that uses the values here: https://github.com/jrvansuita/PickImage/blob/76a4bdfee2f703f89e794e93396296a9b7bb050d/library/src/main/java/com/vansuita/pickimage/img/ImageHandler.java

It seems to be applied to `Bitmap.createScaledBitmap()`, which I think takes pixels, but that would create consistent results. That class also includes some scaling logic that adjusts those values.

Thanks for any help!

**Comment by jrvansuita** [comment]
Take a look:

```
    private BitmapFactory.Options getOptions() throws FileNotFoundException {
        BitmapFactory.Options options = new BitmapFactory.Options();
        options.inJustDecodeBounds = true;
        decodeStream(context.getContentResolver().openInputStream(uri), null, options);

        int w = options.outWidth;
        int h = options.outHeight;
        int scale = 1;
        while (true) {
            if (w / 2 < setup.getWidth() || h / 2 < setup.getHeight())
                break;

            w /= 2;
            h /= 2;
            scale *= 2;
        }

        options = new BitmapFactory.Options();
        options.inSampleSize = scale;
        return options;
    }


```

It will scale down the image Width and/or Height by 2 (dividing by 2), until the Width and the Height of the given image is equal or below the value of "maxSize".

**Comment by makeitTim** [comment]
Thanks for the response!

I don't follow, why are you dividing by 2? And doesn't this loop, if larger than the max, always stop BEFORE the max because it does the check before dividing by 2? My results above always ended up with width and height larger than the setMaxSize. It should be `while ( w > setup.getWidth() || h > setup.getHeight() ) {`?

I've done stuff like this, dividing by two, when processing OpenGL textures because you'd scale things in texture sizes which are powers of 2 --- but that shouldn't be a limitation here as far as image byte processing.

Wouldn't something like `setMaxWidthOrHeight` make more sense, then if the width were greater than that value: save the original aspectRatio, set `width = max` and `height = max * aspectRatio`. Or if BitmapFactory takes a scale factor, just `width / max`?
