### ISSUE TITLE
Support of vector files 

### ISSUE THREAD

**Issue by yoali11** [jrvansuita/PickImage#56]
Reopening of issue #50.
"Fatal Exception: android.content.res.Resources$NotFoundExceptionFile res/drawable/ic_cell_camera.xml from drawable resource ID #0x7f0700b8. If the resource you are trying to use is a vector resource, you may be referencing it in an unsupported way. See AppCompatDelegate.setCompatVectorFromResourcesEnabled() for more info. "

I need a way to pass a drawable as an icon, and not the _int_ reference. To use a Vector image as icon. :-)

Update:
`val pickSetup = pickSetup().setCameraIcon(R.drawable.ic_cell_camera)`

This accepts only an _int_ reference to the drawable. I want to use it like:

`val pickSetup = PickSetup().setCameraIcon(VectorDrawableCompat.create(activity.resources, R.drawable.ic_cell_album, null))`

So the argument would be a Drawable.

This would enable me to use a vectorised image also.

**Comment by jrvansuita** [comment]
Yes, I need to code this func.

**Comment by jrvansuita** [comment]
I would be great to see some contribution.
