### ISSUE TITLE
Opening from a fragment

### ISSUE THREAD

**Issue by SebastienFCT** [jrvansuita/PickImage#6]
Hey there,

I was wondering if there was any way to launch the PickImageDialog from a fragment.

We could call `PickImageDialog.on((MainActivity) getActivity(), setup);` but I guess at this point the main activity will be set as the listener while I'd like the current fragment to be able to be the listener.

Thanks in advance

**Comment by jrvansuita** [comment]
I think it is not possible. Can you try to teach me how could I get this done?

**Comment by jrvansuita** [comment]
Hi, I figured how, look this:


```
PickImageDialog.on(getActivity())
                        .setOnBitmapResult(new IPickResult.IPickResultBitmap() {
                            @Override
                            public void onPickImageResult(Bitmap bitmap) {
                                //TODO: getting the bitmap.
                            }
                        }).setOnBitmapResult(new IPickResult.IPickResultBitmap() {
                            @Override
                            public void onPickImageResult(Bitmap bitmap) {
                                 //TODO: getting the bitmap.
                        }
                        }).setOnError(new IPickResult.IPickError() {
                            @Override
                            public void onPickError(Exception e) {
                                //TODO: handle the error.
                        }
                        });
```

**Comment by SebastienFCT** [comment]
Awesome man! I didn't though about implementing the callback locally, nice catch!

I was checking the code and not sure, but I think you could create a new constructor for your PickImageDialog taking a FragmentManager (instead of activity) and also a custom Object Listener (which would implements the different listeners).

Anyway, if you are interested about it, I could eventually work on it as soon as I get some time (not yet for sure), otherwise your solution seems good! (I didn't try yet, week end...)

**Comment by jrvansuita** [comment]
Gotta brotha. Check it out.
