### ISSUE TITLE
In oreo camera is not working

### ISSUE THREAD

**Issue by abrar105** [jrvansuita/PickImage#60]
This is shown for oreo... when i use camera option. Failed to find provider for user 0

and this is caused for security reason may be.
see this..
https://stackoverflow.com/questions/47032767/java-lang-securityexception-failed-to-find-provider-questions-for-user-0-expec

and i also hope you will add crop function too.

**Comment by mp205** [comment]
same here

**Comment by jrvansuita** [comment]
Guys, one of you could make a pull request and fix it. I would be great to see some contribution.

**Comment by insearching** [comment]
The issue was fixed in 2.1.5 release. Please verify.

**Comment by batman-tdk** [comment]
not working on 2.1.5
Failed to find provider  for user 0; expected to find a valid ContentProvider for this authority

**Comment by batman-tdk** [comment]
working on 2.15
