### ISSUE TITLE
onActivityResult bug

### ISSUE THREAD

**Issue by Wounded-Shadow** [jrvansuita/PickImage#61]
if you override "onActivityResult" method in your activity so the picker didn't call its "onPickResult" function but call your onActivityresult.

**Comment by jrvansuita** [comment]
Make a pull request and fix it please. I'm out of time to fix this.

**Comment by mba3gar** [comment]
how did you solve it? just remove the @override from onActivity result ? or what shall we do ?

**Comment by Artem-Klyuev** [comment]
@mba3gar just call super.onActivityResult() in your @override
