### ISSUE TITLE
Gallery option not displayed when using system dialog

### ISSUE THREAD

**Issue by eugeneroz** [jrvansuita/PickImage#62]
Used the following code:
`PickSetup pickSetup = new PickSetup(); 
pickSetup.setCameraToPictures(false);
 pickSetup.setSystemDialog(true);    
 PickImageDialog.build(pickSetup).setOnPickResult(this).show(getActivity().getSupportFragmentManager());`

Device:
Samsung Galaxy S5
Android version: 6.0.1

![screenshot_2018-02-25-13-54-57](https://user-images.githubusercontent.com/5417880/36641186-014d202c-1a34-11e8-807e-84b990c79d29.png)

**Comment by jrvansuita** [comment]
Yeap, in some devices it will not work as expected
