### ISSUE TITLE
Cancel in dialog

### ISSUE THREAD

**Issue by leslieharland** [jrvansuita/PickImage#66]
Please fix the cancel button so that it won't crash my app...

**Comment by prashantguleria** [comment]
You can implement it yourself like this.

PickImageDialog.build(new PickSetup()
                        .setCameraIcon(com.vansuita.pickimage.R.mipmap.camera_colored)
                        .setGalleryIcon(com.vansuita.pickimage.R.mipmap.gallery_colored)
                        .setButtonOrientation(LinearLayoutCompat.VERTICAL)
                .setSystemDialog(false))
                        .setOnPickCancel(
                                new IPickCancel() {
                                    @Override
                                    public void onCancelClick() {
                                        //TODO: do what you have to if user clicked cancel
                                        Toast.makeText(UserWelcomeProfileActivity.this, "User Cancelled!", Toast.LENGTH_LONG).show();
                                    }
                                }
                        ).show(this);
