### ISSUE TITLE
 dismiss dialog and setPickTypes issues

### ISSUE THREAD

**Issue by hamdalaye** [jrvansuita/PickImage#7]
Hi,

This is a great project but :

How to dismiss the dialog if for example we want to write our own pick images functionalities ?

`setup.setPickTypes(EPickTypes.GALERY, EPickTypes.CAMERA)` not found.

Cheers!

**Comment by hamdalaye** [comment]
Update,

For the dialog dismiss issue, I found a way to "cheat" a little bit by looking into your code. I changed 

`PickImageDialog.on(this, setup);`  by : 

`PickImageDialog d = PickImageDialog.newInstance(setup);
 d.show(this.getSupportFragmentManager(), "dialog");`

and called `d.dismiss() before launching activity`

**Comment by jrvansuita** [comment]
Fixed on v2.0.0. See the readme file to check how to dismiss.
