### ISSUE TITLE
Opens gallery instead of camera

### ISSUE THREAD

**Issue by ghost** [jrvansuita/PickImage#72]
PickImage opens gallery instead of camera when I do the following steps:
1. open PickImage dialog and click on gallery button
2. I get permissions request and I accept permissions
3. gallery opens
4. click back and open PickImage dialog again
5. this time I click on camera button
6. I get permissions request and I accept permissions
7. Now gallery opens instead of camera

**Comment by jaroslavhavelik** [comment]
This is solved in my fork of library: https://github.com/jaroslavhavelik/PickImage. It's solved by permission dispatcher, so its not so lightweight right now, but its working.
Stuff that I didn't done - permission not gradted propagating etc. (can be done on activity)
