### ISSUE TITLE
not going through onPickResult()

### ISSUE THREAD

**Issue by PalladiumDium** [jrvansuita/PickImage#73]
`private void buildPickImage() {
        PickImageDialog.build(new PickSetup())
                .setOnPickResult(new IPickResult() {
                    @Override
                    public void onPickResult(PickResult r) {
                        Log.d(TAG, "onPickResult: HERE I AM");
                        Uri resultUri = r.getUri();
...........
}
`

I created a methode for build a PickImage, and despite selecting and taking a picture the tag "Log.d(TAG, "onPickResult: HERE I AM");" is never executed :(

**Comment by PalladiumDium** [comment]
When using into fragments be aware of how you Override onActivityResult on your host Activity ! My bad

**Comment by majedalmoqbeli** [comment]
@PalladiumDium 
How did you fix it with fragment??
