### ISSUE TITLE
Issues on Nougat 24+

### ISSUE THREAD

**Issue by AMahmoud991** [jrvansuita/PickImage#8]
file:// scheme is now not allowed to be attached with Intent on targetSdkVersion 24 (Android Nougat) so the app crash with with the following error file:///storage/emulated/0/IPickResult/temp.jpg exposed beyond app through ClipData.Item.getUri()
Check this article https://inthecheesefactory.com/blog/how-to-share-access-to-file-with-fileprovider-on-android-nougat/en

**Comment by jrvansuita** [comment]
Fixed.
