### ISSUE TITLE
Vertical image rotated from camera or gallery.

### ISSUE THREAD

**Issue by jcfatjo** [jrvansuita/PickImage#86]
I'm getting a rotated image after taking a **vertical** image from camera or selecting it from gallery.

- This is the configuration of **PickImageDialog**:

`PickImageDialog.build(new PickSetup()`
`    .setTitle("Select an image")`
`    .setCancelText("Cancel")`
`    .setCancelTextColor(R.color.colorPrimary)`
`    .setFlip(true)`
`    .setCameraButtonText("Camera")`
`    .setGalleryButtonText(getString("Gallery")`
`).show(this);`

- And this is the **onPickResult**:

`public void onPickResult(PickResult pickResult) {`
`    if (pickResult.getError() == null) {`
`        ivImage.setImageURI(null);`
`        ivImage.setImageURI(pickResult.getUri());`
`    } else {`
`        Log.d(LOG_ACTIVITY, "Error selecting an image.");`
`    }`
`}`

Can you tell me if you can reproduce this behavior?

Edit: There is a clean project using only the library.
[TestSelectImage.zip](https://github.com/jrvansuita/PickImage/files/2120155/TestSelectImage.zip)

**Comment by rbarriuso** [comment]
Is this issue reproduced generally on any device?

**Comment by jcfatjo** [comment]
The issue was reproduced in:

- Samsung Galaxy Tab A (Android 6.0.1)
- Samsung Galaxy Tab E (Android 4.4.4.)
- Samsung Galaxy J7 2017 (Android 7.0)
- Android emulator (Android 7.0)

It couldn't be reproduced in:

- BQ Aquaris U2 (Android 7.1.2)

**Comment by rbarriuso** [comment]
Reproduced on Pixel XL API 25 (Android 7) emulator and Sony D2301 API 22 (Android 5.1.1) device.

**Comment by yogeshpaliyal** [comment]
please remove .setFlip(true)
