### ISSUE TITLE
remove WRITE_EXTERNAL_STORAGE permission

### ISSUE THREAD

**Issue by iceberg1369** [jrvansuita/PickImage#9]
the library should remove 
 **uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE**
there is no need to access external storage directly because images get picked through standard intent.
the library works OK although the above permission revoked (tested in Android M)

**Comment by jrvansuita** [comment]
Yes it's necessary to have declared WRITE_EXTERNAL_STORAGE.
The image is saved on external storage.

![screenshot_20170111-162331](https://cloud.githubusercontent.com/assets/12175215/21867112/bfaaab82-d81a-11e6-8802-8771a387080f.png)
