### ISSUE TITLE
PickImage Provider With Android File Provider

### ISSUE THREAD

**Issue by saddahussain** [jrvansuita/PickImage#94]
How to use pick image provider with android's file provider?
I can only use one at this time.

![screenshot_11](https://user-images.githubusercontent.com/20544271/45484129-980add80-b76c-11e8-868b-a23e583e86a8.png)

**Comment by saddahussain** [comment]
I want to use both but that gives error.

**Comment by anitoledo** [comment]
I'm trying to do the same, did you find a solution?
